version: '2'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    ## This is the port the app will default to unless overwritten
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

    volumes:
      - ../:/opt/app/
      - /opt/app/node_modules

    # links:
    #   - postgres

  # postgres:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
